server:
  port: 8080

app:
  platform-server-url: ${APP_PLATFORM_SERVER_URL:http://localhost:8081}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: IoTServer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drone_control?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mqtt:
  broker-url: tcp://localhost:1883
  client-id: drone-control-server